# Generated by Django 3.1.4 on 2020-12-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20201229_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='model',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
