# Generated by Django 3.1.4 on 2020-12-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acces_token', models.CharField(default='', max_length=150, unique=True)),
                ('refresh_token', models.CharField(default='', max_length=150, unique=True)),
                ('expires_in', models.DateTimeField()),
                ('trained_model', models.CharField(default='', max_length=150, unique=True)),
                ('uid', models.CharField(default='', max_length=150, unique=True)),
            ],
        ),
    ]
