# Generated by Django 3.1.4 on 2021-01-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='model',
        ),
        migrations.AddField(
            model_name='user',
            name='pic_url',
            field=models.CharField(default='none', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
