# Generated by Django 3.1.4 on 2021-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210109_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pred_count',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
