# Generated by Django 3.1.4 on 2021-01-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_pred_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pred_count',
            field=models.IntegerField(default=0),
        ),
    ]
